### PR TITLE
I-#326 cancel badge showing on post details and my activity page

### LINKED ISSUE #326: Fix frontend and backend issues
1. birthday should not have time in it @Biplob14 ✅
2. add profile button doesn't fit in screen @EbrahimAli-RU 
3. the notification is not showing details @EbrahimAli-RU 
4. add profile showing something went wrong in some phone (example: in sakib vai's phone (need to sit with him)) @EbrahimAli-RU 
5. post is not showing if its canceled, or running - @Rezwanul-Haque
6. The donation complete button missing @EbrahimAli-RU ✅
7. post title in the top has lots of padding when doing preview build
8. post card in my activity content had some padding issues @EbrahimAli-RU  ✅
9. In public Post Details page go to map not implemented. @EbrahimAli-RU ✅
10. alert after 1 hour of donation time for complete donation
11. profile edit PR @Biplob14 ✅
12. dont show missing fields in details page @EbrahimAli-RU ✅
13. if i accepted a request, when i goto the details page again. it should show request already accepted @EbrahimAli-RU ✅
14. update public post get partition to sort by date and also skip the old blood groups - **backend**
15. move the local notification time to env
16. last vaccination date and last donation date should not be required fields - backend and frontend
17. change height to string. And notify frontend - **backend**
18. add google map icon in donation map
19. when cancel modal opens opacity not applied in the device.  @Rezwanul-Haque 
20. add profile page scroll issue @Rezwanul-Haque

### PR DESCRIPTION
**Pull request by Rezwanul-Haque**
Fixes #326 

Resolves #
Used when the changes in the pull request indirectly resolve another issue.

- [x] Does not depend on other PRs
- [ ] Depends on other PR being merged first: #

## What kind of change does this PR introduce (check at least one)

- [ ] Bugfix
- [x] Improvement
- [ ] New feature
- [ ] Refactor
- [ ] Infrastructure
- [ ] Other (please specify)

## How would you describe the changes in a changelog (1-2 lines)?
fixes and improvement related to #326 item 5

Provide a brief overview of the changes introduced in this pull request.

## Related Issues/PRs (optional)

Link to the relevant issue(s) or provide a clear description of the problem or feature being addressed.

## How to test

- [ ] Needs regression testing (add QA needed label)

## Checklist

- [x] I have tested these changes locally and they function as expected.
- [ ] I have added or updated necessary documentation to reflect the changes.
- [x] I have followed the project's coding style and guidelines.
- [ ] I have added appropriate test coverage to ensure the changes are functioning correctly.
- [ ] I have checked for any potential conflicts with other branches or pull requests.
- [ ] I have updated necessary OpenAPI specs

## Reviewer Request (optional)

If you have any specific requests or suggestions for reviewers, mention them here.

## Screenshots (optional)

If applicable, provide any additional screenshots or GIFs that showcase the changes made in this pull request.

## Demo Link (optional)

If applicable, provide a link to a live demo or deployment where the changes can be reviewed.

## Known Issues (optional)

If there are any known issues or limitations with the changes made in this pull request, describe them here.

## Additional Notes (optional)

Add any additional notes or comments you think are relevant to this pull request.

## Deploy risk & follow up

Please assess risk & follow up on deployment of this PR. Elaborate your choice if selecting anything other than 'No risk'.

- [x] No risk
- [ ] Low
- [ ] High

### CODE REVIEW

File: clients/mobile/src/donationWorkflow/types.ts [hunk 1]
```diff
@@ -1,11 +1,12 @@
 import { DonationDTO } from '../../../../commons/dto/DonationDTO'
 
-export type StatusType = 'ACCEPTED' | 'IGNORE' | 'PENDING'
+export type StatusType = 'ACCEPTED' | 'IGNORE' | 'PENDING' | 'CANCELLED'
 
 export const STATUS: Record<string, StatusType> = {
```
Comment (mahinuzzaman) [inline clients/mobile/src/donationWorkflow/types.ts:5]: should this variable name be `DONATION_STATUS`?

File: clients/mobile/src/components/badge/index.tsx [hunk 2]
```diff
@@ -0,0 +1,95 @@
...
+ */
+interface BadgeProps {
+  text: string | number;
+  containerStyle?: StyleProp<ViewStyle>;
+  textStyle?: StyleProp<TextStyle>;
+  iconName?: string;
+}
+
+/**
+ * Badge Component
```
Comment (mahinuzzaman) [inline clients/mobile/src/components/badge/index.tsx:22]: Do we need these much comments?

File: clients/mobile/src/donationWorkflow/types.ts (hunk 1 above)
Comment (sakibstark11) [reply clients/mobile/src/donationWorkflow/types.ts:5]: This

File: clients/mobile/src/components/badge/index.tsx (hunk 2 above)
Comment (Rezwanul-Haque) [reply clients/mobile/src/components/badge/index.tsx:22]: I added this because it's help us to check how to use the component otherwise we have to find the usage example.

File: clients/mobile/src/donationWorkflow/types.ts (hunk 1 above)
Comment (Rezwanul-Haque) [reply clients/mobile/src/donationWorkflow/types.ts:5]: It's already named like this and I don't know the full context that's why I didn't change the name

**Review by mahinuzzaman — APPROVED** [review]
