### PR TITLE
I 326 minor changes

### LINKED ISSUE #326: Fix frontend and backend issues
1. birthday should not have time in it @Biplob14 ✅
2. add profile button doesn't fit in screen @EbrahimAli-RU 
3. the notification is not showing details @EbrahimAli-RU 
4. add profile showing something went wrong in some phone (example: in sakib vai's phone (need to sit with him)) @EbrahimAli-RU 
5. post is not showing if its canceled, or running - @Rezwanul-Haque
6. The donation complete button missing @EbrahimAli-RU ✅
7. post title in the top has lots of padding when doing preview build
8. post card in my activity content had some padding issues @EbrahimAli-RU  ✅
9. In public Post Details page go to map not implemented. @EbrahimAli-RU ✅
10. alert after 1 hour of donation time for complete donation
11. profile edit PR @Biplob14 ✅
12. dont show missing fields in details page @EbrahimAli-RU ✅
13. if i accepted a request, when i goto the details page again. it should show request already accepted @EbrahimAli-RU ✅
14. update public post get partition to sort by date and also skip the old blood groups - **backend**
15. move the local notification time to env
16. last vaccination date and last donation date should not be required fields - backend and frontend
17. change height to string. And notify frontend - **backend**
18. add google map icon in donation map
19. when cancel modal opens opacity not applied in the device.  @Rezwanul-Haque 
20. add profile page scroll issue @Rezwanul-Haque

### PR DESCRIPTION
**Pull request by Biplob14**
Fixes #326 

Resolves #
- On request ignore, hit backend ignore API to keep record
- Bottom extra margin remove on profile page
- Remove duplicate profile update service
- Changed label to appropriate meaning
- Location icon adjustment on profile
- Test file for add personal info update

- [x] Does not depend on other PRs
- [ ] Depends on other PR being merged first: #

## What kind of change does this PR introduce (check at least one)

- [x] Bugfix
- [x] Improvement
- [x] New feature
- [x] Refactor
- [ ] Infrastructure
- [ ] Other (please specify)

Please assess risk & follow up on deployment of this PR. Elaborate your choice if selecting anything other than 'No risk'.

- [x] No risk
- [ ] Low
- [ ] High

### CODE REVIEW

**Review by mahinuzzaman — APPROVED** [review]

File: clients/mobile/src/donationWorkflow/donationPosts/donorResponse/hooks/useResponseDonationRequest.ts [hunk 1]
```diff
@@ -103,8 +106,26 @@ export const useResponseDonationRequest = (): useResponseDonationRequestReturnTy
...
+    setError(null)
+    const isString = (value: unknown): value is string => typeof value === 'string'
+    const requestPayload: Partial<IgnoreRequestParams> = {
+      requestPostId: isString(bloodRequest.requestPostId) ? bloodRequest.requestPostId : '',
+      seekerId: isString(bloodRequest.seekerId) ? bloodRequest.seekerId : '',
+      createdAt: isString(bloodRequest.createdAt) ? bloodRequest.createdAt : '',
+      status: STATUS.IGNORE
+    }
+    const response = await updateMyResponses(requestPayload, fetchClient)
+    console.log('requestPayload: ', requestPayload, '## response: ', response)
```
Comment (EbrahimAli-RU) [inline clients/mobile/src/donationWorkflow/donationPosts/donorResponse/hooks/useResponseDonationRequest.ts:122]: ?

File: clients/mobile/src/components/inputElement/SearchMultiSelect.tsx [hunk 2]
```diff
@@ -100,7 +100,7 @@ const SearchMultiSelect = ({ name, label, isVisible, setIsVisible, error, onChan
       <View style={{ position: 'relative' }}>
         <View style={styles.dropdown}>
           <TextInput
-            placeholder='Search Preferred Location'
+            placeholder='Search Preferred hospital/health care'
```
Comment (Rezwanul-Haque) [inline clients/mobile/src/components/inputElement/SearchMultiSelect.tsx:103]: Capitalize this as `Search Preferred` was capitalized

File: clients/mobile/src/donationWorkflow/donationPosts/donorResponse/hooks/useResponseDonationRequest.ts [hunk 3]
```diff
@@ -103,8 +106,26 @@ export const useResponseDonationRequest = (): useResponseDonationRequestReturnTy
     }
   }
 
-  const handleIgnore = (): void => {
-    navigation.navigate(SCREENS.POSTS)
+  const handleIgnore = async(): Promise<void> => {
+    if (bloodRequest === null) return
```
Comment (EbrahimAli-RU) [inline clients/mobile/src/donationWorkflow/donationPosts/donorResponse/hooks/useResponseDonationRequest.ts:110]: Should we just return null or we should show any error to the user?

File: clients/mobile/src/donationWorkflow/donationPosts/donorResponse/hooks/useResponseDonationRequest.ts [hunk 4]
```diff
@@ -103,8 +106,26 @@ export const useResponseDonationRequest = (): useResponseDonationRequestReturnTy
...
+
+    setIsLoading(true)
+    setError(null)
```
Comment (EbrahimAli-RU) [inline clients/mobile/src/donationWorkflow/donationPosts/donorResponse/hooks/useResponseDonationRequest.ts:113]: Do we need to set `null` to `setError` here?

File: clients/mobile/src/donationWorkflow/donationPosts/donorResponse/hooks/useResponseDonationRequest.ts [hunk 5]
```diff
@@ -103,8 +106,26 @@ export const useResponseDonationRequest = (): useResponseDonationRequestReturnTy
...
+    const isString = (value: unknown): value is string => typeof value === 'string'
```
Comment (EbrahimAli-RU) [inline clients/mobile/src/donationWorkflow/donationPosts/donorResponse/hooks/useResponseDonationRequest.ts:114]: Should this method be here?

File: clients/mobile/src/donationWorkflow/donationPosts/donorResponse/hooks/useResponseDonationRequest.ts [hunk 6]
```diff
@@ -103,8 +106,26 @@ export const useResponseDonationRequest = (): useResponseDonationRequestReturnTy
...
+      createdAt: isString(bloodRequest.createdAt) ? bloodRequest.createdAt : '',
+      status: STATUS.IGNORE
+    }
+    const response = await updateMyResponses(requestPayload, fetchClient)
+    console.log('requestPayload: ', requestPayload, '## response: ', response)
+
+    if (response.status === 200) {
+      navigation.navigate(SCREENS.POSTS)
+    } else {
+      throw new Error('Could not complete ignore response')
```
Comment (EbrahimAli-RU) [inline clients/mobile/src/donationWorkflow/donationPosts/donorResponse/hooks/useResponseDonationRequest.ts:127]: I don't see `try-catch` if it throws then I think the app will crash.

File: clients/mobile/src/donationWorkflow/donationPosts/donorResponse/hooks/useResponseDonationRequest.ts (hunk 5 above)
Comment (Rezwanul-Haque) [inline clients/mobile/src/donationWorkflow/donationPosts/donorResponse/hooks/useResponseDonationRequest.ts:114]: return type should be boolean, right?

File: clients/mobile/src/myActivity/context/MyActivityProvider.tsx [hunk 7]
```diff
@@ -5,7 +5,7 @@ import { DonationData, extractErrorMessage, formatDonations } from '../../donati
 import { useUserProfile } from '../../userWorkflow/context/UserProfileContext'
 import useFetchData from '../../setup/clients/useFetchData'
 import storageService from '../../utility/storageService'
-import { UserProfile } from '../../userWorkflow/services/userProfileService'
+import { UserProfile } from '../../userWorkflow/services/userProfileServices'
```
Comment (Rezwanul-Haque) [inline clients/mobile/src/myActivity/context/MyActivityProvider.tsx:8]: why plural?

File: clients/mobile/src/userWorkflow/context/UserProfileContext.tsx [hunk 8]
```diff
@@ -1,6 +1,6 @@
 import React, { createContext, useState, useContext, ReactNode } from 'react'
 import { useFetchClient } from '../../setup/clients/useFetchClient'
-import { fetchUserProfileFromApi, UserProfile } from '../services/userProfileService'
+import { fetchUserProfileFromApi, UserProfile } from '../services/userProfileServices'
```
Comment (Rezwanul-Haque) [inline clients/mobile/src/userWorkflow/context/UserProfileContext.tsx:3]: same

File: clients/mobile/src/donationWorkflow/createUpdateDonation/Donation.tsx [hunk 9]
```diff
@@ -80,7 +80,7 @@ const CreateBloodRequest = () => {
 
           <View style={[styles.fieldSpacing, styles.extraBottomMargin]}>
             <DateTimePickerComponent
-              label="Time and Date"
+              label="Donation Time and Date"
```
Comment (sakibstark11) [inline clients/mobile/src/donationWorkflow/createUpdateDonation/Donation.tsx:83]: you read date and time not time and date

File: clients/mobile/src/donationWorkflow/donationPosts/donorResponse/hooks/useResponseDonationRequest.ts (hunk 1 above)
Comment (sakibstark11) [reply clients/mobile/src/donationWorkflow/donationPosts/donorResponse/hooks/useResponseDonationRequest.ts:122]: ?

File: clients/mobile/src/myActivity/context/MyActivityProvider.tsx (hunk 7 above)
Comment (sakibstark11) [reply clients/mobile/src/myActivity/context/MyActivityProvider.tsx:8]: yeah

Comment (Biplob14) [reply clients/mobile/src/myActivity/context/MyActivityProvider.tsx:8]: There is multiple service in that file.

Comment (Rezwanul-Haque) [reply clients/mobile/src/myActivity/context/MyActivityProvider.tsx:8]: That's the point bhai, `userProfileService` should only export the functions/methods  which are related to user profile. It's shouldn't contain other service. For my opinion should be singular not plural.

File: clients/mobile/src/donationWorkflow/donationPosts/donorResponse/hooks/useResponseDonationRequest.ts (hunk 4 above)
Comment (Biplob14) [reply clients/mobile/src/donationWorkflow/donationPosts/donorResponse/hooks/useResponseDonationRequest.ts:113]: Resetting the state here for being in safe zone as this state is used in multiple places.

File: clients/mobile/src/components/inputElement/SearchMultiSelect.tsx [hunk 10]
```diff
@@ -100,7 +100,7 @@ const SearchMultiSelect = ({ name, label, isVisible, setIsVisible, error, onChan
       <View style={{ position: 'relative' }}>
         <View style={styles.dropdown}>
           <TextInput
-            placeholder='Search Preferred Location'
+            placeholder='Search Preferred Hospital/Health care CentreSearch Preferred Hospital/Health care'
```
Comment (sakibstark11) [inline clients/mobile/src/components/inputElement/SearchMultiSelect.tsx:103]: is this a typo Hospital/Health care CentreSearch Preferred Hospital/Health care

File: clients/mobile/src/donationWorkflow/donationPosts/donorResponse/UI/ResponseDonationRequest.tsx [hunk 11]
```diff
@@ -65,7 +65,9 @@ const ResponseDonationRequest = () => {
                 />
                 <View style={styles.requestText}>
                   <Text style={styles.primaryCaption}>Looking for</Text>
-                  <Text style={styles.highlightedText}>{bloodRequest.bloodQuantity ?? 0} {bloodRequest.requestedBloodGroup}(ve) blood</Text>
+                  <Text style={styles.highlightedText}>
+                    {bloodRequest.bloodQuantity ?? 0} {bloodRequest.requestedBloodGroup}(ve) blood
```
Comment (sakibstark11) [inline clients/mobile/src/donationWorkflow/donationPosts/donorResponse/UI/ResponseDonationRequest.tsx:69]: so 1 blood? shouldn't it be 1 bags of blood

File: clients/mobile/src/donationWorkflow/donationPosts/donorResponse/UI/ResponseDonationRequest.tsx [hunk 12]
```diff
@@ -159,8 +163,23 @@ const ResponseDonationRequest = () => {
...
+        {!isLoading && !(isRequestAccepted || (Boolean(isRequestAlreadyAccepted))) &&
+        <Button
+          text="Ignore"
+          buttonStyle={styles.ignoreButton}
+          textStyle={{ color: theme.colors.black }}
+          onPress={() => {
+            void handleIgnore()
+          }} />}
+        <Button
+          text={isRequestAccepted || (Boolean(isRequestAlreadyAccepted)) ? 'Request Accepted' : 'Accept Request'}
```
Comment (sakibstark11) [inline clients/mobile/src/donationWorkflow/donationPosts/donorResponse/UI/ResponseDonationRequest.tsx:175]: why does the second one need type casting

File: clients/mobile/src/donationWorkflow/donationPosts/donorResponse/hooks/useResponseDonationRequest.ts (hunk 4 above)
Comment (sakibstark11) [reply clients/mobile/src/donationWorkflow/donationPosts/donorResponse/hooks/useResponseDonationRequest.ts:109]: @EbrahimAli-RU why are we not using the pre built useFetch function?

Comment (EbrahimAli-RU) [reply clients/mobile/src/donationWorkflow/donationPosts/donorResponse/hooks/useResponseDonationRequest.ts:109]: Yes, we can use the `useFetch` hook to call API here. While I did the review, I forgot that we have a hook to call API.

File: clients/mobile/src/donationWorkflow/donationPosts/donorResponse/hooks/useResponseDonationRequest.ts (hunk 1 above)
Comment (Biplob14) [reply clients/mobile/src/donationWorkflow/donationPosts/donorResponse/hooks/useResponseDonationRequest.ts]: removed

File: clients/mobile/src/components/inputElement/SearchMultiSelect.tsx (hunk 2 above)
Comment (Biplob14) [reply clients/mobile/src/components/inputElement/SearchMultiSelect.tsx]: changed it to `Search Preferred Hospital/Health care`

File: clients/mobile/src/donationWorkflow/donationPosts/donorResponse/hooks/useResponseDonationRequest.ts (hunk 3 above)
Comment (Biplob14) [reply clients/mobile/src/donationWorkflow/donationPosts/donorResponse/hooks/useResponseDonationRequest.ts]: Changed it and throwing error instead.

File: clients/mobile/src/donationWorkflow/donationPosts/donorResponse/hooks/useResponseDonationRequest.ts (hunk 4 above)
Comment (Biplob14) [reply clients/mobile/src/donationWorkflow/donationPosts/donorResponse/hooks/useResponseDonationRequest.ts]: Implemented `useFetchData` hook on ignore request

File: clients/mobile/src/donationWorkflow/donationPosts/donorResponse/hooks/useResponseDonationRequest.ts (hunk 6 above)
Comment (Biplob14) [reply clients/mobile/src/donationWorkflow/donationPosts/donorResponse/hooks/useResponseDonationRequest.ts]: Implemented `try-catch`

File: clients/mobile/src/donationWorkflow/donationPosts/donorResponse/UI/ResponseDonationRequest.tsx (hunk 12 above)
Comment (Biplob14) [reply clients/mobile/src/donationWorkflow/donationPosts/donorResponse/UI/ResponseDonationRequest.tsx:175]: Had a TS error. Fixed it.

File: clients/mobile/src/donationWorkflow/donationPosts/donorResponse/hooks/useResponseDonationRequest.ts [hunk 13]
```diff
@@ -97,21 +110,50 @@ export const useResponseDonationRequest = (): useResponseDonationRequestReturnTy
...
+    const { requestPostId, seekerId, createdAt } = bloodRequest
+
+    const requestPayload = {
+      requestPostId,
+      seekerId,
+      createdAt,
+      status: STATUS.IGNORED
+    }
+
+    try {
```
[the remark this answers is not in the document]
Comment (Biplob14) [reply clients/mobile/src/donationWorkflow/donationPosts/donorResponse/hooks/useResponseDonationRequest.ts]: Removed

File: clients/mobile/src/donationWorkflow/donationPosts/donorResponse/UI/ResponseDonationRequest.tsx (hunk 11 above)
Comment (Biplob14) [reply clients/mobile/src/donationWorkflow/donationPosts/donorResponse/UI/ResponseDonationRequest.tsx:69]: We have a function which already formatting and adding 'Bags' string with the quantity. So, It'll show something like `2 Bags B+ blood`

**Review by Rezwanul-Haque — APPROVED** [review]
