### PR TITLE
Fix Issues with Swipe Refresh, Request Status Updates, Post Completion, and Donor List Visibility

### LINKED ISSUE #374: Cannot `swipe refresh` after network disconnects
## Bug Report

Once the network is disconnected, and `Network Response Failed` message is shown in a view, there is no way to fetch data without exiting the application. The swipe refresh does not work

**Severity:**

- [ ] P0 (Critical)
- [ ] P1 (High Priority)
- [x] P2 (Medium Priority)
- [ ] P3 (Low Priority)

**Steps to Reproduce:**
Open the app -> turn off internet and refresh in the `My Activity` page -> Then turn internet back on -> swipe refresh does not work.
The same happens in the main page when not fetched from cache. For testing use cases, as the data after opening the app is fetched from the cache every time until the cache is invalidated, it will not reproduce.

## Possible Solution (optional)

Guess: The swipe refresh component is not added to the `Network Response Failed` component. Maybe adding that will fix the issue.

### PR DESCRIPTION
**Pull request by EbrahimAli-RU**
Fixes #374 #376 #381 #384 

When the network is not available, it is considered an error, which prevents the main content from rendering. To address this, I have implemented an error component and render it with a refresh controller.

If a request is canceled or completed, I have disabled the update and cancel buttons.

If no donor is found for a post, when the user clicks the "Yes, Manage" button, it first checks if any donor is available. If a donor is present, it moves to the select page. If no donor is present, clicking the "Yes, Manage" button will call the API to complete the post.

Resolves #
Used when the changes in the pull request indirectly resolve another issue.

- [x] Does not depend on other PRs
- [ ] Depends on other PR being merged first: #

## What kind of change does this PR introduce (check at least one)

- [x] Bugfix
- [ ] Improvement
- [ ] New feature
- [ ] Refactor
- [ ] Infrastructure
- [ ] Other (please specify)

## How would you describe the changes in a changelog (1-2 lines)?

Provide a brief overview of the changes introduced in this pull request.

## Related Issues/PRs (optional)

Link to the relevant issue(s) or provide a clear description of the problem or feature being addressed.

## How to test

- [ ] Needs regression testing (add QA needed label)

## Checklist

- [x] I have tested these changes locally and they function as expected.
- [ ] I have added or updated necessary documentation to reflect the changes.
- [x] I have followed the project's coding style and guidelines.
- [ ] I have added appropriate test coverage to ensure the changes are functioning correctly.
- [ ] I have checked for any potential conflicts with other branches or pull requests.
- [ ] I have updated necessary OpenAPI specs

## Reviewer Request (optional)

If you have any specific requests or suggestions for reviewers, mention them here.

## Screenshots (optional)

If applicable, provide any additional screenshots or GIFs that showcase the changes made in this pull request.

## Demo Link (optional)

If applicable, provide a link to a live demo or deployment where the changes can be reviewed.

## Known Issues (optional)

If there are any known issues or limitations with the changes made in this pull request, describe them here.

## Additional Notes (optional)

Add any additional notes or comments you think are relevant to this pull request.

## Deploy risk & follow up

Please assess risk & follow up on deployment of this PR. Elaborate your choice if selecting anything other than 'No risk'.

- [x] No risk
- [ ] Low
- [ ] High

### CODE REVIEW

File: clients/mobile/src/components/donation/PostCard.tsx [hunk 1]
```diff
@@ -205,99 +226,99 @@ export const PostCard: React.FC<PostCardProps> = React.memo(({
...
-                    text="URGENT"
-                    containerStyle={styles.urgentBadge}
-                    textStyle={styles.urgentText}
-                    iconName='triangle-exclamation'
-                />
-            )}
           </View>
+          {post.urgencyLevel === UrgencyLevel.URGENT && (
+            <Badge
+              text="URGENT"
```
Comment (sakibstark11) [inline clients/mobile/src/components/donation/PostCard.tsx:247]: shouldn't this be from the enum

**Review by mahinuzzaman — APPROVED** [review]

**Review by mahinuzzaman — APPROVED** [review]
